export interface DailyReflection {
  day: number;
  text: string;
  author?: string;
  source?: string;
}

// 365 daily reflections for recovery - mix of AA literature, wisdom, and inspiration
export const dailyReflections: DailyReflection[] = [
  { day: 1, text: "One day at a time. This simple phrase has saved countless lives by keeping us focused on the present moment.", author: "AA Wisdom", source: "Daily Reflection" },
  { day: 2, text: "Progress, not perfection. We strive for growth, knowing we will never be perfect—and that's okay.", author: "AA Wisdom", source: "Daily Reflection" },
  { day: 3, text: "The only requirement for membership is a desire to stop drinking. No fees, no obligations, just willingness.", source: "AA Preamble" },
  { day: 4, text: "We are going to know a new freedom and a new happiness. The promises are real, and they await us.", source: "Big Book, p. 83" },
  { day: 5, text: "Rarely have we seen a person fail who has thoroughly followed our path. The program works if we work it.", source: "Big Book, p. 58" },
  { day: 6, text: "Came to believe that a Power greater than ourselves could restore us to sanity. Opening our minds to new possibilities.", source: "Step 2" },
  { day: 7, text: "Let go and let God. Surrender isn't weakness—it's the doorway to real strength.", author: "AA Wisdom" },
  { day: 8, text: "The bondage of self is the root of our suffering. Freedom comes from getting outside ourselves.", source: "Big Book" },
  { day: 9, text: "Honesty, open-mindedness, and willingness. These three spiritual principles are the keys to recovery.", author: "AA Slogan" },
  { day: 10, text: "We admitted we were powerless over alcohol—that our lives had become unmanageable. The first step toward freedom.", source: "Step 1" },
  { day: 11, text: "HALT: Never let yourself get too Hungry, Angry, Lonely, or Tired. Self-care is recovery care.", author: "AA Wisdom" },
  { day: 12, text: "The person I was yesterday is not the person I am today. Recovery brings transformation.", author: "Recovery Wisdom" },
  { day: 13, text: "Fear of people and of economic insecurity will leave us. Trust the process.", source: "Big Book, p. 84" },
  { day: 14, text: "Made a decision to turn our will and our lives over to the care of God as we understood Him.", source: "Step 3" },
  { day: 15, text: "We will not regret the past nor wish to shut the door on it. Our experiences make us who we are.", source: "Big Book, p. 83" },
  { day: 16, text: "Keep coming back. It works if you work it, and you're worth it.", author: "AA Slogan" },
  { day: 17, text: "The more you give away, the more you keep. Service to others strengthens our own recovery.", author: "AA Wisdom" },
  { day: 18, text: "Made a searching and fearless moral inventory of ourselves. Courage to look within.", source: "Step 4" },
  { day: 19, text: "We will comprehend the word serenity and we will know peace. Calm becomes our new normal.", source: "Big Book, p. 83" },
  { day: 20, text: "First things first. Priorities become clearer when we're not clouded by addiction.", author: "AA Slogan" },
  { day: 21, text: "Admitted to God, to ourselves, and to another human being the exact nature of our wrongs.", source: "Step 5" },
  { day: 22, text: "Self-seeking will slip away. We become more interested in others than ourselves.", source: "Big Book, p. 84" },
  { day: 23, text: "Live and let live. Acceptance of others brings peace to ourselves.", author: "AA Slogan" },
  { day: 24, text: "Were entirely ready to have God remove all these defects of character.", source: "Step 6" },
  { day: 25, text: "Our whole attitude and outlook upon life will change. The lens through which we see the world transforms.", source: "Big Book, p. 84" },
  { day: 26, text: "Easy does it. Recovery isn't a race—take it at your own pace.", author: "AA Slogan" },
  { day: 27, text: "Humbly asked Him to remove our shortcomings. Humility opens the door to growth.", source: "Step 7" },
  { day: 28, text: "That feeling of uselessness and self-pity will disappear. Purpose replaces despair.", source: "Big Book, p. 83" },
  { day: 29, text: "How important is it? Perspective helps us let go of petty grievances.", author: "AA Slogan" },
  { day: 30, text: "Made a list of all persons we had harmed, and became willing to make amends to them all.", source: "Step 8" },
  { day: 31, text: "We will lose interest in selfish things and gain interest in our fellows. Connection heals.", source: "Big Book, p. 84" },
  { day: 32, text: "Think, think, think. Pause before reacting—our first thought isn't always our best thought.", author: "AA Slogan" },
  { day: 33, text: "Made direct amends to such people wherever possible, except when to do so would injure them or others.", source: "Step 9" },
  { day: 34, text: "No matter how far down the scale we have gone, we will see how our experience can benefit others.", source: "Big Book, p. 83" },
  { day: 35, text: "One alcoholic talking to another—that's our secret. Shared experience breaks through isolation.", source: "AA Wisdom" },
  { day: 36, text: "Continued to take personal inventory and when we were wrong promptly admitted it.", source: "Step 10" },
  { day: 37, text: "We will intuitively know how to handle situations which used to baffle us. Wisdom emerges.", source: "Big Book, p. 84" },
  { day: 38, text: "This too shall pass. Everything is temporary—both the good days and the hard ones.", author: "Recovery Wisdom" },
  { day: 39, text: "Sought through prayer and meditation to improve our conscious contact with God as we understood Him.", source: "Step 11" },
  { day: 40, text: "We will suddenly realize that God is doing for us what we could not do for ourselves.", source: "Big Book, p. 84" },
  { day: 41, text: "Serenity is not freedom from the storm, but peace amid the storm.", author: "Recovery Wisdom" },
  { day: 42, text: "Having had a spiritual awakening as the result of these steps, we tried to carry this message to alcoholics.", source: "Step 12" },
  { day: 43, text: "Are these extravagant promises? We think not. They are being fulfilled among us.", source: "Big Book, p. 84" },
  { day: 44, text: "The only thing we have to fear is fear itself. Facing our fears diminishes their power.", author: "Recovery Wisdom" },
  { day: 45, text: "We practice these principles in all our affairs. Recovery isn't just for meetings.", source: "Step 12" },
  { day: 46, text: "Sometimes quickly, sometimes slowly. The promises materialize on their own timeline.", source: "Big Book, p. 84" },
  { day: 47, text: "Courage isn't the absence of fear—it's moving forward despite it.", author: "Recovery Wisdom" },
  { day: 48, text: "I am responsible. When anyone, anywhere, reaches out for help, I want the hand of AA always to be there.", source: "Responsibility Declaration" },
  { day: 49, text: "We have found much of heaven and we have been rocketed into a fourth dimension of existence.", source: "Big Book, p. 25" },
  { day: 50, text: "Gratitude turns what we have into enough. A grateful heart is a recovering heart.", author: "Recovery Wisdom" },
  { day: 51, text: "The spiritual life is not a theory. We have to live it.", source: "Big Book, p. 83" },
  { day: 52, text: "Connection is the opposite of addiction. We heal through relationships.", author: "Johann Hari" },
  { day: 53, text: "Life will take on new meaning. To watch people recover is an experience you must not miss.", source: "Big Book, p. 89" },
  { day: 54, text: "You can't think your way into right acting, but you can act your way into right thinking.", author: "AA Wisdom" },
  { day: 55, text: "Frequent contact with newcomers and with each other is the bright spot of our lives.", source: "Big Book, p. 89" },
  { day: 56, text: "We didn't get here overnight, and we won't recover overnight. Patience with the process.", author: "Recovery Wisdom" },
  { day: 57, text: "The problem has been removed. It does not exist for us. We are neither cocky nor afraid.", source: "Big Book, p. 85" },
  { day: 58, text: "Rock bottom became the solid foundation on which I rebuilt my life.", author: "J.K. Rowling" },
  { day: 59, text: "We have a way out on which we can absolutely agree. Unity in purpose.", source: "Big Book, p. 17" },
  { day: 60, text: "Comparison is the thief of joy. Your recovery journey is yours alone.", author: "Theodore Roosevelt" },
  { day: 61, text: "Faith without works is dead. Action is required.", source: "Big Book" },
  { day: 62, text: "The wound is the place where the light enters you.", author: "Rumi" },
  { day: 63, text: "Half measures availed us nothing. We stood at the turning point.", source: "Big Book, p. 59" },
  { day: 64, text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
  { day: 65, text: "We ask His protection and care with complete abandon. Surrender brings safety.", source: "Big Book, p. 59" },
  { day: 66, text: "Recovery is not a destination but a journey. Enjoy the process.", author: "Recovery Wisdom" },
  { day: 67, text: "Remember that we deal with alcohol—cunning, baffling, powerful! Without help it is too much for us.", source: "Big Book, p. 58" },
  { day: 68, text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
  { day: 69, text: "But there is One who has all power—that One is God. May you find Him now!", source: "Big Book, p. 59" },
  { day: 70, text: "One crack at a time. We can't fix everything at once.", author: "AA Slogan" },
  { day: 71, text: "Our stories disclose what we used to be like, what happened, and what we are like now.", source: "Big Book, p. 58" },
  { day: 72, text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
  { day: 73, text: "If you have decided you want what we have and are willing to go to any length to get it...", source: "Big Book, p. 58" },
  { day: 74, text: "Shame dies when stories are told in safe spaces.", author: "Brené Brown" },
  { day: 75, text: "Then you are ready to take certain steps. Willingness opens doors.", source: "Big Book, p. 58" },
  { day: 76, text: "The comeback is always stronger than the setback.", author: "Recovery Wisdom" },
  { day: 77, text: "With all the earnestness at our command, we beg of you to be fearless and thorough from the very start.", source: "Big Book, p. 58" },
  { day: 78, text: "Every day is a second chance.", author: "Recovery Wisdom" },
  { day: 79, text: "Some of us have tried to hold on to our old ideas and the result was nil until we let go absolutely.", source: "Big Book, p. 58" },
  { day: 80, text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { day: 81, text: "Those who do not recover are people who cannot or will not completely give themselves to this simple program.", source: "Big Book, p. 58" },
  { day: 82, text: "Your present circumstances don't determine where you can go; they merely determine where you start.", author: "Nido Qubein" },
  { day: 83, text: "There are those who suffer from grave emotional and mental disorders, but many of them do recover.", source: "Big Book, p. 58" },
  { day: 84, text: "The only way out is through.", author: "Robert Frost" },
  { day: 85, text: "We thought we could find an easier, softer way. But we could not.", source: "Big Book, p. 58" },
  { day: 86, text: "Healing is not linear.", author: "Recovery Wisdom" },
  { day: 87, text: "At some of these we balked. We understand hesitation. Push through.", source: "Big Book, p. 58" },
  { day: 88, text: "Sometimes the smallest step in the right direction ends up being the biggest step of your life.", author: "Recovery Wisdom" },
  { day: 89, text: "They seem to have been born that way. Compassion for those who struggle.", source: "Big Book, p. 58" },
  { day: 90, text: "You didn't come this far to only come this far.", author: "Recovery Wisdom" },
  { day: 91, text: "Capacity to be honest. This is the key to recovery.", source: "Big Book, p. 58" },
  { day: 92, text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { day: 93, text: "They are naturally incapable of grasping and developing a manner of living which demands rigorous honesty.", source: "Big Book, p. 58" },
  { day: 94, text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { day: 95, text: "Rigorous honesty. Not perfection, but authenticity.", author: "AA Wisdom" },
  { day: 96, text: "Difficult roads often lead to beautiful destinations.", author: "Recovery Wisdom" },
  { day: 97, text: "Their chances are less than average. And yet some still recover. Hope remains.", source: "Big Book, p. 58" },
  { day: 98, text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { day: 99, text: "They are not at fault. Judgment helps no one.", source: "Big Book, p. 58" },
  { day: 100, text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { day: 101, text: "We are without defense against the first drink. Humility keeps us safe.", source: "Big Book" },
  { day: 102, text: "What you resist, persists. Acceptance brings peace.", author: "Carl Jung" },
  { day: 103, text: "The alcoholic is like a tornado roaring his way through the lives of others. Amends help repair the damage.", source: "Big Book" },
  { day: 104, text: "Pain is inevitable. Suffering is optional.", author: "Haruki Murakami" },
  { day: 105, text: "We have concluded to quit for keeps. Permanent sobriety.", source: "Big Book" },
  { day: 106, text: "You were given this life because you are strong enough to live it.", author: "Recovery Wisdom" },
  { day: 107, text: "The alcoholic is an unreasonable person. Understanding helps us accept.", source: "Big Book" },
  { day: 108, text: "Stars can't shine without darkness.", author: "Dolly Parton" },
  { day: 109, text: "We have started upon a course of action that will lead us to a new way of living.", source: "Big Book" },
  { day: 110, text: "When you feel like quitting, think about why you started.", author: "Recovery Wisdom" },
  { day: 111, text: "Service to others is the rent you pay for your room here on earth.", author: "Muhammad Ali" },
  { day: 112, text: "The more sponsors you have, the better. Different perspectives help.", author: "AA Wisdom" },
  { day: 113, text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { day: 114, text: "Sponsorship is a two-way street. Both people grow.", author: "AA Wisdom" },
  { day: 115, text: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama" },
  { day: 116, text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { day: 117, text: "Morning reflection: God, direct my thinking today so that it be divorced of self-pity and fear.", source: "Step 11 Prayer" },
  { day: 118, text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { day: 119, text: "Evening reflection: As I review my day, show me where I have fallen short.", source: "Step 11 Prayer" },
  { day: 120, text: "Life shrinks or expands in proportion to one's courage.", author: "Anaïs Nin" },
  { day: 121, text: "God, I offer myself to Thee—to build with me and to do with me as Thou wilt.", source: "Third Step Prayer" },
  { day: 122, text: "Courage is being scared to death—and saddling up anyway.", author: "John Wayne" },
  { day: 123, text: "Relieve me of the bondage of self, that I may better do Thy will.", source: "Third Step Prayer" },
  { day: 124, text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
  { day: 125, text: "My Creator, I am now willing that you should have all of me, good and bad.", source: "Seventh Step Prayer" },
  { day: 126, text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { day: 127, text: "Remove from me every single defect of character which stands in the way of my usefulness.", source: "Seventh Step Prayer" },
  { day: 128, text: "Grief is the price we pay for love.", author: "Queen Elizabeth II" },
  { day: 129, text: "Grant me strength, as I go out from here, to do your bidding.", source: "Seventh Step Prayer" },
  { day: 130, text: "The mind is everything. What you think you become.", author: "Buddha" },
  { day: 131, text: "Lord, make me a channel of thy peace. Where there is hatred, I may bring love.", source: "St. Francis Prayer" },
  { day: 132, text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
  { day: 133, text: "Where there is wrong, I may bring the spirit of forgiveness.", source: "St. Francis Prayer" },
  { day: 134, text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { day: 135, text: "It is by self-forgetting that one finds. Paradox of service.", source: "St. Francis Prayer" },
  { day: 136, text: "Limit your always and your nevers.", author: "Amy Poehler" },
  { day: 137, text: "It is by dying that one awakens to eternal life. Old self must pass for new self to emerge.", source: "St. Francis Prayer" },
  { day: 138, text: "You don't have to see the whole staircase, just take the first step.", author: "Martin Luther King Jr." },
  { day: 139, text: "God, grant me the serenity to accept the things I cannot change.", source: "Serenity Prayer" },
  { day: 140, text: "Hope is being able to see that there is light despite all of the darkness.", author: "Desmond Tutu" },
  { day: 141, text: "The courage to change the things I can. Action on my part.", source: "Serenity Prayer" },
  { day: 142, text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { day: 143, text: "And the wisdom to know the difference. This is the gift of discernment.", source: "Serenity Prayer" },
  { day: 144, text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
  { day: 145, text: "Living one day at a time. This moment is all we have.", source: "Serenity Prayer" },
  { day: 146, text: "No act of kindness, no matter how small, is ever wasted.", author: "Aesop" },
  { day: 147, text: "Accepting hardship as the pathway to peace. Growth through struggle.", source: "Serenity Prayer" },
  { day: 148, text: "The best and most beautiful things in the world cannot be seen or touched—they must be felt with the heart.", author: "Helen Keller" },
  { day: 149, text: "That I may be reasonably happy in this life. Balance, not perfection.", source: "Serenity Prayer" },
  { day: 150, text: "Sometimes you win, sometimes you learn.", author: "John Maxwell" },
  { day: 151, text: "Supremely happy with Him forever in the next. Eternal perspective.", source: "Serenity Prayer" },
  { day: 152, text: "Resilience is the ability to attack the world with a sense of optimism.", author: "Recovery Wisdom" },
  { day: 153, text: "Set aside prayer: God, help me set aside everything I think I know for an open mind and new experience.", source: "AA Prayer" },
  { day: 154, text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { day: 155, text: "The traditions protect AA. They are not rules but guidelines for unity.", source: "AA Wisdom" },
  { day: 156, text: "We may not be responsible for our disease, but we are responsible for our recovery.", author: "AA Wisdom" },
  { day: 157, text: "Our common welfare should come first; personal recovery depends upon AA unity.", source: "Tradition 1" },
  { day: 158, text: "Kindness is the language which the deaf can hear and the blind can see.", author: "Mark Twain" },
  { day: 159, text: "Our leaders are but trusted servants; they do not govern. Humility in leadership.", source: "Tradition 2" },
  { day: 160, text: "The greatest gift you can give someone is the gift of your time and attention.", author: "Recovery Wisdom" },
  { day: 161, text: "The only requirement for membership is a desire to stop drinking. No barriers.", source: "Tradition 3" },
  { day: 162, text: "Peace begins with a smile.", author: "Mother Teresa" },
  { day: 163, text: "Each group should be autonomous except in matters affecting other groups or AA as a whole.", source: "Tradition 4" },
  { day: 164, text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { day: 165, text: "Each group has but one primary purpose—to carry its message to the alcoholic who still suffers.", source: "Tradition 5" },
  { day: 166, text: "Recovery is an acceptance that your life is in shambles and you have to change.", author: "Jamie Lee Curtis" },
  { day: 167, text: "An AA group ought never endorse, finance, or lend the AA name to any outside enterprise.", source: "Tradition 6" },
  { day: 168, text: "Forgiveness does not change the past, but it does enlarge the future.", author: "Paul Boese" },
  { day: 169, text: "Every AA group ought to be fully self-supporting, declining outside contributions.", source: "Tradition 7" },
  { day: 170, text: "One's dignity may be assaulted, vandalized and cruelly mocked, but it can never be taken away unless it is surrendered.", author: "Michael J. Fox" },
  { day: 171, text: "AA should remain forever nonprofessional, but our service centers may employ special workers.", source: "Tradition 8" },
  { day: 172, text: "Tough times never last, but tough people do.", author: "Robert Schuller" },
  { day: 173, text: "AA, as such, ought never be organized; but we may create service boards or committees.", source: "Tradition 9" },
  { day: 174, text: "You never know how strong you are until being strong is your only choice.", author: "Bob Marley" },
  { day: 175, text: "AA has no opinion on outside issues; hence the AA name ought never be drawn into public controversy.", source: "Tradition 10" },
  { day: 176, text: "The shadow is what we think of it; the tree is the real thing.", author: "Abraham Lincoln" },
  { day: 177, text: "Our public relations policy is based on attraction rather than promotion.", source: "Tradition 11" },
  { day: 178, text: "You can't go back and change the beginning, but you can start where you are and change the ending.", author: "C.S. Lewis" },
  { day: 179, text: "Anonymity is the spiritual foundation of all our traditions, ever reminding us to place principles before personalities.", source: "Tradition 12" },
  { day: 180, text: "Strength doesn't come from what you can do. It comes from overcoming the things you once thought you couldn't.", author: "Rikki Rogers" },
  { day: 181, text: "We strive for progress, not perfection. Growth mindset.", author: "AA Slogan" },
  { day: 182, text: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles Swindoll" },
  { day: 183, text: "Act as if. Sometimes we have to behave our way into right thinking.", author: "AA Wisdom" },
  { day: 184, text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { day: 185, text: "Meeting makers make it. Show up consistently.", author: "AA Slogan" },
  { day: 186, text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
  { day: 187, text: "The therapeutic value of one addict helping another is without parallel.", source: "NA Basic Text" },
  { day: 188, text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { day: 189, text: "The most important words in AA are 'me too.' You are not alone.", author: "AA Wisdom" },
  { day: 190, text: "What we once enjoyed and deeply loved we can never lose, for all that we love deeply becomes part of us.", author: "Helen Keller" },
  { day: 191, text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { day: 192, text: "Character is how you treat those who can do nothing for you.", author: "Recovery Wisdom" },
  { day: 193, text: "Everything will be okay in the end. If it's not okay, it's not the end.", author: "John Lennon" },
  { day: 194, text: "Kind words can be short and easy to speak, but their echoes are truly endless.", author: "Mother Teresa" },
  { day: 195, text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { day: 196, text: "The best revenge is massive success.", author: "Frank Sinatra" },
  { day: 197, text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { day: 198, text: "If you look at what you have in life, you'll always have more.", author: "Oprah Winfrey" },
  { day: 199, text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { day: 200, text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
  { day: 201, text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { day: 202, text: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart" },
  { day: 203, text: "An unexamined life is not worth living.", author: "Socrates" },
  { day: 204, text: "It is never too late to be what you might have been.", author: "George Eliot" },
  { day: 205, text: "You become what you believe.", author: "Oprah Winfrey" },
  { day: 206, text: "I would rather walk with a friend in the dark, than alone in the light.", author: "Helen Keller" },
  { day: 207, text: "Happiness is a butterfly, which when pursued, is always beyond your grasp, but which, if you will sit down quietly, may alight upon you.", author: "Nathaniel Hawthorne" },
  { day: 208, text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
  { day: 209, text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { day: 210, text: "Stay close to people who feel like sunlight.", author: "Recovery Wisdom" },
  { day: 211, text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { day: 212, text: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb" },
  { day: 213, text: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius" },
  { day: 214, text: "To handle yourself, use your head; to handle others, use your heart.", author: "Eleanor Roosevelt" },
  { day: 215, text: "Count your age by friends, not years. Count your life by smiles, not tears.", author: "John Lennon" },
  { day: 216, text: "The truth is rarely pure and never simple.", author: "Oscar Wilde" },
  { day: 217, text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
  { day: 218, text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" },
  { day: 219, text: "Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.", author: "Dr. Seuss" },
  { day: 220, text: "A friend may well be reckoned the masterpiece of nature.", author: "Ralph Waldo Emerson" },
  { day: 221, text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
  { day: 222, text: "For every minute you are angry you lose sixty seconds of happiness.", author: "Ralph Waldo Emerson" },
  { day: 223, text: "The only way to have a friend is to be one.", author: "Ralph Waldo Emerson" },
  { day: 224, text: "What you do speaks so loudly that I cannot hear what you say.", author: "Ralph Waldo Emerson" },
  { day: 225, text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
  { day: 226, text: "Remember that sometimes not getting what you want is a wonderful stroke of luck.", author: "Dalai Lama" },
  { day: 227, text: "Our prime purpose in this life is to help others. And if you can't help them, at least don't hurt them.", author: "Dalai Lama" },
  { day: 228, text: "Sleep is the best meditation.", author: "Dalai Lama" },
  { day: 229, text: "Give the ones you love wings to fly, roots to come back, and reasons to stay.", author: "Dalai Lama" },
  { day: 230, text: "Love is the absence of judgment.", author: "Dalai Lama" },
  { day: 231, text: "If you think you are too small to make a difference, try sleeping with a mosquito.", author: "Dalai Lama" },
  { day: 232, text: "The world doesn't make sense, so why should I paint pictures that do?", author: "Pablo Picasso" },
  { day: 233, text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
  { day: 234, text: "Others have seen what is and asked why. I have seen what could be and asked why not.", author: "Pablo Picasso" },
  { day: 235, text: "The meaning of life is to find your gift. The purpose of life is to give it away.", author: "Pablo Picasso" },
  { day: 236, text: "Never a failure, always a lesson.", author: "Rihanna" },
  { day: 237, text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { day: 238, text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle" },
  { day: 239, text: "No great mind has ever existed without a touch of madness.", author: "Aristotle" },
  { day: 240, text: "Happiness depends upon ourselves.", author: "Aristotle" },
  { day: 241, text: "The antidote for fifty enemies is one friend.", author: "Aristotle" },
  { day: 242, text: "Those who know, do. Those that understand, teach.", author: "Aristotle" },
  { day: 243, text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { day: 244, text: "There is no great genius without a mixture of madness.", author: "Aristotle" },
  { day: 245, text: "Wishing to be friends is quick work, but friendship is a slow ripening fruit.", author: "Aristotle" },
  { day: 246, text: "In all things of nature there is something of the marvelous.", author: "Aristotle" },
  { day: 247, text: "The aim of art is to represent not the outward appearance of things, but their inward significance.", author: "Aristotle" },
  { day: 248, text: "Excellence is never an accident. It is always the result of high intention, sincere effort, and intelligent execution.", author: "Aristotle" },
  { day: 249, text: "We are what we repeatedly do. Excellence is not an act, but a habit.", author: "Will Durant on Aristotle" },
  { day: 250, text: "Education is an ornament in prosperity and a refuge in adversity.", author: "Aristotle" },
  { day: 251, text: "Good habits formed at youth make all the difference.", author: "Aristotle" },
  { day: 252, text: "Without friends, no one would want to live, even if he had all other goods.", author: "Aristotle" },
  { day: 253, text: "We praise a man who feels angry on the right grounds and against the right persons and also in the right manner.", author: "Aristotle" },
  { day: 254, text: "To write well, express yourself like the common people, but think like a wise man.", author: "Aristotle" },
  { day: 255, text: "It is not enough to win a war; it is more important to organize the peace.", author: "Aristotle" },
  { day: 256, text: "Moral excellence comes about as a result of habit. We become just by doing just acts.", author: "Aristotle" },
  { day: 257, text: "You will never do anything in this world without courage. It is the greatest quality of the mind next to honor.", author: "Aristotle" },
  { day: 258, text: "Happiness is a quality of the soul... not a function of one's material circumstances.", author: "Aristotle" },
  { day: 259, text: "Learning is not child's play; we cannot learn without pain.", author: "Aristotle" },
  { day: 260, text: "The worst form of inequality is to try to make unequal things equal.", author: "Aristotle" },
  { day: 261, text: "The energy of the mind is the essence of life.", author: "Aristotle" },
  { day: 262, text: "We make war that we may live in peace.", author: "Aristotle" },
  { day: 263, text: "There was never a genius without a tincture of madness.", author: "Aristotle" },
  { day: 264, text: "I count him braver who overcomes his desires than him who conquers his enemies.", author: "Aristotle" },
  { day: 265, text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
  { day: 266, text: "To perceive is to suffer.", author: "Aristotle" },
  { day: 267, text: "It is the function of art to renew our perception.", author: "Aristotle" },
  { day: 268, text: "Dignity does not consist in possessing honors, but in deserving them.", author: "Aristotle" },
  { day: 269, text: "Man is by nature a social animal.", author: "Aristotle" },
  { day: 270, text: "The young are permanently in a state resembling intoxication.", author: "Aristotle" },
  { day: 271, text: "Even when laws have been written down, they ought not always to remain unaltered.", author: "Aristotle" },
  { day: 272, text: "He who can, does. He who cannot, teaches.", author: "George Bernard Shaw" },
  { day: 273, text: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
  { day: 274, text: "A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.", author: "George Bernard Shaw" },
  { day: 275, text: "The single biggest problem in communication is the illusion that it has taken place.", author: "George Bernard Shaw" },
  { day: 276, text: "Progress is impossible without change, and those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { day: 277, text: "You see things; you say, 'Why?' But I dream things that never were; and I say 'Why not?'", author: "George Bernard Shaw" },
  { day: 278, text: "We don't stop playing because we grow old; we grow old because we stop playing.", author: "George Bernard Shaw" },
  { day: 279, text: "There are no secrets better kept than the secrets that everybody guesses.", author: "George Bernard Shaw" },
  { day: 280, text: "Beware of false knowledge; it is more dangerous than ignorance.", author: "George Bernard Shaw" },
  { day: 281, text: "The reasonable man adapts himself to the world; the unreasonable one persists in trying to adapt the world to himself.", author: "George Bernard Shaw" },
  { day: 282, text: "People who say it cannot be done should not interrupt those who are doing it.", author: "George Bernard Shaw" },
  { day: 283, text: "First love is only a little foolishness and a lot of curiosity.", author: "George Bernard Shaw" },
  { day: 284, text: "Success does not consist in never making mistakes but in never making the same one a second time.", author: "George Bernard Shaw" },
  { day: 285, text: "Imagination is the beginning of creation.", author: "George Bernard Shaw" },
  { day: 286, text: "We are made wise not by the recollection of our past, but by the responsibility for our future.", author: "George Bernard Shaw" },
  { day: 287, text: "Some look at things that are, and ask why. I dream of things that never were and ask why not?", author: "George Bernard Shaw" },
  { day: 288, text: "A government that robs Peter to pay Paul can always depend on the support of Paul.", author: "George Bernard Shaw" },
  { day: 289, text: "The more things a man is ashamed of, the more respectable he is.", author: "George Bernard Shaw" },
  { day: 290, text: "There is no love sincerer than the love of food.", author: "George Bernard Shaw" },
  { day: 291, text: "Those who cannot change their minds cannot change anything.", author: "George Bernard Shaw" },
  { day: 292, text: "Alcohol is a very necessary article.", author: "George Bernard Shaw" },
  { day: 293, text: "Activity is the only road to knowledge.", author: "George Bernard Shaw" },
  { day: 294, text: "Hatred is the coward's revenge for being intimidated.", author: "George Bernard Shaw" },
  { day: 295, text: "The worst sin toward our fellow creatures is not to hate them, but to be indifferent to them.", author: "George Bernard Shaw" },
  { day: 296, text: "The only way to avoid being miserable is not to have enough leisure to wonder whether you are happy or not.", author: "George Bernard Shaw" },
  { day: 297, text: "Life is not meant to be easy, my child; but take courage: it can be delightful.", author: "George Bernard Shaw" },
  { day: 298, text: "There is nothing so bad or so good that you will not find an Englishman doing it.", author: "George Bernard Shaw" },
  { day: 299, text: "He who has never hoped can never despair.", author: "George Bernard Shaw" },
  { day: 300, text: "Marriage is an alliance entered into by a man who can't sleep with the window shut, and a woman who can't sleep with the window open.", author: "George Bernard Shaw" },
  { day: 301, text: "Self-denial is not a virtue: it is only the effect of prudence on prudence.", author: "George Bernard Shaw" },
  { day: 302, text: "My reputation grows with every failure.", author: "George Bernard Shaw" },
  { day: 303, text: "An election is a moral horror, as bad as a battle except for the blood.", author: "George Bernard Shaw" },
  { day: 304, text: "Beauty is all very well at first sight; but who ever looks at it when it has been in the house three days?", author: "George Bernard Shaw" },
  { day: 305, text: "One man that has a mind and knows it can always beat ten men who haven't and don't.", author: "George Bernard Shaw" },
  { day: 306, text: "The man with a toothache thinks everyone happy whose teeth are sound.", author: "George Bernard Shaw" },
  { day: 307, text: "If you have an apple and I have an apple and we exchange these apples then you and I will still each have one apple.", author: "George Bernard Shaw" },
  { day: 308, text: "Better keep yourself clean and bright; you are the window through which you must see the world.", author: "George Bernard Shaw" },
  { day: 309, text: "There are two tragedies in life. One is to lose your heart's desire. The other is to gain it.", author: "George Bernard Shaw" },
  { day: 310, text: "If you cannot get rid of the family skeleton, you may as well make it dance.", author: "George Bernard Shaw" },
  { day: 311, text: "A broken heart is a very pleasant complaint for a man in London if he has a comfortable income.", author: "George Bernard Shaw" },
  { day: 312, text: "I never resist temptation, because I have found that things that are bad for me do not tempt me.", author: "George Bernard Shaw" },
  { day: 313, text: "The law is equal before all of us; but we are not all equal before the law.", author: "George Bernard Shaw" },
  { day: 314, text: "Virtue is insufficient temptation.", author: "George Bernard Shaw" },
  { day: 315, text: "Patriotism is your conviction that this country is superior to all other countries because you were born in it.", author: "George Bernard Shaw" },
  { day: 316, text: "Chess is a foolish expedient for making idle people believe they are doing something very clever when they are only wasting their time.", author: "George Bernard Shaw" },
  { day: 317, text: "Silence is the most perfect expression of scorn.", author: "George Bernard Shaw" },
  { day: 318, text: "We have no more right to consume happiness without producing it than to consume wealth without producing it.", author: "George Bernard Shaw" },
  { day: 319, text: "He knows nothing and thinks he knows everything. That points clearly to a political career.", author: "George Bernard Shaw" },
  { day: 320, text: "Democracy is a device that ensures we shall be governed no better than we deserve.", author: "George Bernard Shaw" },
  { day: 321, text: "A gentleman is one who puts more into the world than he takes out.", author: "George Bernard Shaw" },
  { day: 322, text: "The possibilities are numerous once we decide to act and not react.", author: "George Bernard Shaw" },
  { day: 323, text: "Never believe in anything until it has been officially denied.", author: "Otto von Bismarck" },
  { day: 324, text: "Politics is the art of the possible.", author: "Otto von Bismarck" },
  { day: 325, text: "Fools learn from experience. I prefer to learn from the experience of others.", author: "Otto von Bismarck" },
  { day: 326, text: "The main thing is to make history, not to write it.", author: "Otto von Bismarck" },
  { day: 327, text: "When you say you agree to a thing in principle you mean that you have not the slightest intention of carrying it out in practice.", author: "Otto von Bismarck" },
  { day: 328, text: "The secret of politics? Make a good treaty with Russia.", author: "Otto von Bismarck" },
  { day: 329, text: "Laws are like sausages, it is better not to see them being made.", author: "Otto von Bismarck" },
  { day: 330, text: "The less people know about how sausages and laws are made, the better they'll sleep at night.", author: "Otto von Bismarck" },
  { day: 331, text: "Preventive war is like committing suicide out of fear of death.", author: "Otto von Bismarck" },
  { day: 332, text: "Only a fool learns from his own mistakes. The wise man learns from the mistakes of others.", author: "Otto von Bismarck" },
  { day: 333, text: "A really great man is known by three signs: generosity in the design, humanity in the execution, moderation in success.", author: "Otto von Bismarck" },
  { day: 334, text: "People never lie so much as after a hunt, during a war or before an election.", author: "Otto von Bismarck" },
  { day: 335, text: "The great questions of the day will not be settled by means of speeches and majority decisions but by iron and blood.", author: "Otto von Bismarck" },
  { day: 336, text: "To retain respect for sausages and laws, one must not watch them in the making.", author: "Otto von Bismarck" },
  { day: 337, text: "I have seen the future, and it works.", author: "Lincoln Steffens" },
  { day: 338, text: "The louder he talked of his honor, the faster we counted our spoons.", author: "Ralph Waldo Emerson" },
  { day: 339, text: "Common sense is genius dressed in its working clothes.", author: "Ralph Waldo Emerson" },
  { day: 340, text: "Once you make a decision, the universe conspires to make it happen.", author: "Ralph Waldo Emerson" },
  { day: 341, text: "Hitch your wagon to a star.", author: "Ralph Waldo Emerson" },
  { day: 342, text: "To be great is to be misunderstood.", author: "Ralph Waldo Emerson" },
  { day: 343, text: "All life is an experiment. The more experiments you make the better.", author: "Ralph Waldo Emerson" },
  { day: 344, text: "Nothing great was ever achieved without enthusiasm.", author: "Ralph Waldo Emerson" },
  { day: 345, text: "The only reward of virtue is virtue; the only way to have a friend is to be one.", author: "Ralph Waldo Emerson" },
  { day: 346, text: "Our greatest glory is not in never failing, but in rising up every time we fail.", author: "Ralph Waldo Emerson" },
  { day: 347, text: "Though we travel the world over to find the beautiful, we must carry it with us, or we find it not.", author: "Ralph Waldo Emerson" },
  { day: 348, text: "It is one of the most beautiful compensations of life that no man can sincerely try to help another without helping himself.", author: "Ralph Waldo Emerson" },
  { day: 349, text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { day: 350, text: "What is a weed? A plant whose virtues have not yet been discovered.", author: "Ralph Waldo Emerson" },
  { day: 351, text: "The invariable mark of wisdom is to see the miraculous in the common.", author: "Ralph Waldo Emerson" },
  { day: 352, text: "Adopt the pace of nature: her secret is patience.", author: "Ralph Waldo Emerson" },
  { day: 353, text: "Most of the shadows of this life are caused by standing in one's own sunshine.", author: "Ralph Waldo Emerson" },
  { day: 354, text: "People only see what they are prepared to see.", author: "Ralph Waldo Emerson" },
  { day: 355, text: "The earth laughs in flowers.", author: "Ralph Waldo Emerson" },
  { day: 356, text: "To know even one life has breathed easier because you have lived. This is to have succeeded.", author: "Ralph Waldo Emerson" },
  { day: 357, text: "Always do what you are afraid to do.", author: "Ralph Waldo Emerson" },
  { day: 358, text: "Make the most of yourself....for that is all there is of you.", author: "Ralph Waldo Emerson" },
  { day: 359, text: "The years teach much which the days never know.", author: "Ralph Waldo Emerson" },
  { day: 360, text: "Don't be too timid and squeamish about your actions. All life is an experiment.", author: "Ralph Waldo Emerson" },
  { day: 361, text: "Nothing can bring you peace but yourself.", author: "Ralph Waldo Emerson" },
  { day: 362, text: "Every artist was first an amateur.", author: "Ralph Waldo Emerson" },
  { day: 363, text: "The greatest gift is a portion of thyself.", author: "Ralph Waldo Emerson" },
  { day: 364, text: "We aim above the mark to hit the mark.", author: "Ralph Waldo Emerson" },
  { day: 365, text: "Write it on your heart that every day is the best day in the year. No man has learned anything rightly, until he knows that every day is Doomsday.", author: "Ralph Waldo Emerson" }
];

// Helper function to get today's reflection
export function getTodaysReflection(): DailyReflection {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);
  
  // Day of year is 1-365 (or 366 in leap year), array is 0-indexed but our days start at 1
  return dailyReflections[dayOfYear - 1] || dailyReflections[0];
}

// Helper to get a specific day's reflection (1-365)
export function getReflectionByDay(day: number): DailyReflection {
  const safeDay = Math.max(1, Math.min(365, day));
  return dailyReflections[safeDay - 1];
}

// Get current day of year (1-365)
export function getCurrentDayOfYear(): number {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const oneDay = 1000 * 60 * 60 * 24;
  return Math.floor(diff / oneDay);
}
